config/routes.rb
Rails.application.routes.draw do
  resources :images
  resources :user_regions
  resources :regions
  resources :places
  resources :countries
  resources :states
  resources :cities
  resources :companies
  resources :user_profiles
  devise_for :users
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :companies
end

app/models/company.rb
class Company < ApplicationRecord
	has_many :places, dependent: :destroy
	belongs_to :city
	belongs_to :state
	belongs_to :country
end

app/models/country.rb
class Country < ApplicationRecord
	has_many :companies
end

app/models/image.rb
class Image < ApplicationRecord
	belongs_to :user
	has_one_attached :photo
end

app/models/node.rb
class Node < ApplicationRecord
	belongs_to :place
end

app/models/place.rb
class Place < ApplicationRecord
	has_one :node, dependent: :destroy
	belongs_to :company
	accepts_nested_attributes_for :node
end

app/models/region.rb
class Region < ApplicationRecord
	has_many :user_regions, dependent: :destroy
end

app/models/state.rb
class State < ApplicationRecord
	has_many :companies
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  USER_ROLES = {
    'normal_user': 'normal_user',
    'manager': 'manager',
    'admin': 'admin'
  }.freeze
  enum user_role: USER_ROLES
  has_rich_text :notes

  has_many :user_regions, dependent: :destroy
  has_one :image, dependent: :destroy
  validates :start_date, :end_date, presence: true
  validate :end_date_is_after_start_date
  accepts_nested_attributes_for :image

  def is_normal_user?
    user_role == 'normal_user'
  end

  def is_manager?
    user_role == 'manager'
  end

  def is_admin?
    user_role == 'admin'
  end

#######
private
#######

def end_date_is_after_start_date
  return if end_date.blank? || start_date.blank?
  if end_date < start_date
    errors.add(:end_date, "cannot be before the start date") 
  end 
end
end

app/models/user_region.rb
class UserRegion < ApplicationRecord
	belongs_to :user
	belongs_to :region
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /user or /user.json
  def index
    if current_user.is_admin?
    @users = User.all
  elsif current_user.is_manager?
    @users = User.where(company_id: current_user.company_id)
  else
    @users = User.where(id: current_user.id)
    end
      
  end

  # GET /user/1 or /user/1.json
  def show
  end

  # GET /user/new
  def new
    @user = User.new
    @image = Image.new
    authorize @user
  end

  # GET /user/1/edit
  def edit
  	@image = Image.new
  end

  # POST /user or /user.json
  def create
    @user = User.new(user_params)
     authorize @user

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_profile_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user/1 or /user/1.json
  def update
    authorize @user
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_profile_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user/1 or /user/1.json
  def destroy
    authorize @user
    @user.destroy

    respond_to do |format|
      format.html { redirect_to user_profiles_url, notice: "user was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :start_date, :end_date, :monthly_charge,
               :user_role, :is_active, :notes, :company_id, image_attributes: {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/user_profiles/_form.html.erb
  <div class="input-container">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name, autofocus: true %>
  </div>
  <div class="input-container">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name, autofocus: true %>
  </div>
  <div class="input-container">
    <%= f.label :startDate %><br />
    <%= f.date_field :start_date, autofocus: true %>
  </div>

  <div class="input-container">
    <%= f.label :startDate %><br />
    <%= f.date_field :end_date, autofocus: true %>
  </div>
  
  <div class="input-container">
    <%= f.label :monthly_charge %><br />
    <%= f.number_field :monthly_charge, autofocus: true %>
  </div>
  <div class="input-container">
    <%= f.label :email %>
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>
  <div class="custom-select">
     <%#= f.label :company_name %>
     <%= f.collection_select :company_id, Company.order(:id), :id, :name %>
  </div>

   <div class="custom-select">
    <%#= f.label :Role %>
    <%= f.select :user_role, User::USER_ROLES.keys.to_a %>
  </div>
  <div class="custom-select">
    <%#= f.label :active %>
    <%= f.check_box :is_active %>
  </div>
  <%= f.fields_for :image, @image do |field|%>
  <div class="input-container">
    <%= field.label :photo %>
    <%= field.file_field :photo %>
  </div>
  <% end %>

  <div class="input-container">
    <%= f.label :notes %>
    <%= f.rich_text_area :notes %>
  </div>
 <!--  -->
  <div class="send-container">
    <%= f.submit "Update" %>
  </div>
<%= render 'partials/js_partial' %>

app/views/user_profiles/edit.html.erb
<h1>Editing User</h1>
<%= form_with(model: @user, url: user_profile_path, method: 'patch') do |f|%>
<section>
<%= render 'form', user: @user, f: f  %>

<%= link_to 'Show', user_profile_path(@user) %> |
<%= link_to 'Back', user_profiles_path %>
<% end%>
</section>

app/views/user_profiles/index.html.erb
<h1>User</h1>

<table class="zui-table">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last name</th>
      <th>Active</th>
      <th>Email</th>
      <th>show</th>
      <th>edit</th>
      <th>delete</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @users.each do |user_profile| %>
      <tr>
        <td><%= user_profile.first_name %></td>
        <td><%= user_profile.last_name %></td>
        <td><%= user_profile.is_active %></td>
        <td><%= user_profile.email %></td>
        <td><%= link_to 'Show', user_profile_path(user_profile) %></td>
        <td><%= link_to 'Edit', edit_user_profile_path(user_profile) %></td>
        <td><%= link_to 'Destroy', user_profile_path(user_profile), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New user_profile', new_user_registration_path %>

app/views/user_profiles/new.html.erb
<h1>New Company</h1>
<%= form_with(model: @user, url: new_user_profile_path, method: 'post') do |f|%>
<%= render 'form', user: @user, f: f %>
<% end%>

<%= link_to 'Back', companies_path %>

app/views/user_profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Is active:</strong>
  <%= @user.is_active %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @user.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @user.end_date %>
</p>

<p>
  <strong>Monthly charge:</strong>
  <%= @user.monthly_charge %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong >user role:</strong>
  <%= @user.user_role %>
</p>

<p>
  <strong>Company:</strong>
  <%= @user.company_id %>
</p>

<% if @user.image.present?%>
<div class="img-container">
<%= image_tag (@user.image.photo)%>
<% end%>
</div>

<%= link_to 'Edit', edit_user_profile_path(@user) %> 
<%= link_to 'Back', user_profiles_path %>