config/routes.rb
Rails.application.routes.draw do
  resources :images
  resources :user_regions
  resources :regions
  resources :places
  resources :countries
  resources :states
  resources :cities
  resources :companies
  resources :user_profiles
  devise_for :users
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :companies
end

app/models/company.rb
class Company < ApplicationRecord
	has_many :places, dependent: :destroy
	belongs_to :city
	belongs_to :state
	belongs_to :country
end

app/models/country.rb
class Country < ApplicationRecord
	has_many :companies
end

app/models/image.rb
class Image < ApplicationRecord
	belongs_to :user
	has_one_attached :photo
end

app/models/node.rb
class Node < ApplicationRecord
	belongs_to :place
end

app/models/place.rb
class Place < ApplicationRecord
	has_one :node, dependent: :destroy
	belongs_to :company
	accepts_nested_attributes_for :node
end

app/models/region.rb
class Region < ApplicationRecord
	has_many :user_regions, dependent: :destroy
end

app/models/state.rb
class State < ApplicationRecord
	has_many :companies
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  USER_ROLES = {
    'normal_user': 'normal_user',
    'manager': 'manager',
    'admin': 'admin'
  }.freeze
  enum user_role: USER_ROLES
  has_rich_text :notes

  has_many :user_regions, dependent: :destroy
  has_one :image, dependent: :destroy
  validates :start_date, :end_date, presence: true
  validate :end_date_is_after_start_date
  accepts_nested_attributes_for :image

  def is_normal_user?
    user_role == 'normal_user'
  end

  def is_manager?
    user_role == 'manager'
  end

  def is_admin?
    user_role == 'admin'
  end

#######
private
#######

def end_date_is_after_start_date
  return if end_date.blank? || start_date.blank?
  if end_date < start_date
    errors.add(:end_date, "cannot be before the start date") 
  end 
end
end

app/models/user_region.rb
class UserRegion < ApplicationRecord
	belongs_to :user
	belongs_to :region
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/user_regions_controller.rb
class UserRegionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user_region, only: %i[ show edit update destroy ]

  # GET /user_regions or /user_regions.json
  def index
    @user_regions = UserRegion.all
  end

  # GET /user_regions/1 or /user_regions/1.json
  def show
  end

  # GET /user_regions/new
  def new
    @user_region = UserRegion.new
  end

  # GET /user_regions/1/edit
  def edit
  end

  # POST /user_regions or /user_regions.json
  def create
    @user_region = UserRegion.new(user_region_params)

    respond_to do |format|
      if @user_region.save
        format.html { redirect_to user_region_url(@user_region), notice: "User region was successfully created." }
        format.json { render :show, status: :created, location: @user_region }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_region.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_regions/1 or /user_regions/1.json
  def update
    respond_to do |format|
      if @user_region.update(user_region_params)
        format.html { redirect_to user_region_url(@user_region), notice: "User region was successfully updated." }
        format.json { render :show, status: :ok, location: @user_region }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_region.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_regions/1 or /user_regions/1.json
  def destroy
    @user_region.destroy

    respond_to do |format|
      format.html { redirect_to user_regions_url, notice: "User region was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_region
      @user_region = UserRegion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_region_params
      params.require(:user_region).permit( :region_id, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/user_regions_helper.rb
module UserRegionsHelper
	def all_user_list
		users = User.all
		#users = [users]

	end
end

app/views/user_regions/_form.html.erb
<%= form_with(model: user_region) do |form| %>
<section>
  <% if user_region.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_region.errors.count, "error") %> prohibited this user_region from being saved:</h2>

      <ul>
        <% user_region.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <%= form.label :user %>
  <div class="custom-select">
    <%= form.collection_select :user_id, User.order(:id), :id, :email  %>
  </div>

    <%= form.label :regions %>
  <div class="custom-select">
    <%= form.collection_select :region_id, Region.order(:id), :id, :region_name, multiple: true  %>
  </div>

  <div class="send-container">
    <%= form.submit %>
  </div>
<% end %>
</section>
<%= render 'partials/js_partial' %>

app/views/user_regions/edit.html.erb
<h1>Editing User Region</h1>

<%= render 'form', user_region: @user_region %>

<%= link_to 'Show', @user_region %> |
<%= link_to 'Back', user_regions_path %>

app/views/user_regions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Regions</h1>

<table class="zui-table">
  <thead>
    <tr>
      <th>User</th>
      <th>Region</th>
      <th>show</th>
      <th>edit</th>
      <th>delete</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_regions.each do |user_region| %>
      <tr>
        <td><%= user_region.user&.email%></td>
        <td><%= user_region.region&.region_name%></td>
        <td><%= link_to 'Show', user_region %></td>
        <td><%= link_to 'Edit', edit_user_region_path(user_region) %></td>
        <td><%= link_to 'Destroy', user_region, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Region', new_user_region_path %>

app/views/user_regions/new.html.erb
<h1>New User Region</h1>

<%= render 'form', user_region: @user_region %>

<%= link_to 'Back', user_regions_path %>

app/views/user_regions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Region name:</strong>
  <%= @user_region.region&.region_name %>
</p>

<p>
  <strong>User:</strong>
  <%= @user_region.user&.email %>
</p>
<%= link_to 'Edit', edit_user_region_path(@user_region) %> |
<%= link_to 'Back', user_regions_path %>