config/routes.rb
Rails.application.routes.draw do
  resources :images
  resources :user_regions
  resources :regions
  resources :places
  resources :countries
  resources :states
  resources :cities
  resources :companies
  resources :user_profiles
  devise_for :users
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :companies
end

app/models/company.rb
class Company < ApplicationRecord
	has_many :places, dependent: :destroy
	belongs_to :city
	belongs_to :state
	belongs_to :country
end

app/models/country.rb
class Country < ApplicationRecord
	has_many :companies
end

app/models/image.rb
class Image < ApplicationRecord
	belongs_to :user
	has_one_attached :photo
end

app/models/node.rb
class Node < ApplicationRecord
	belongs_to :place
end

app/models/place.rb
class Place < ApplicationRecord
	has_one :node, dependent: :destroy
	belongs_to :company
	accepts_nested_attributes_for :node
end

app/models/region.rb
class Region < ApplicationRecord
	has_many :user_regions, dependent: :destroy
end

app/models/state.rb
class State < ApplicationRecord
	has_many :companies
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  USER_ROLES = {
    'normal_user': 'normal_user',
    'manager': 'manager',
    'admin': 'admin'
  }.freeze
  enum user_role: USER_ROLES
  has_rich_text :notes

  has_many :user_regions, dependent: :destroy
  has_one :image, dependent: :destroy
  validates :start_date, :end_date, presence: true
  validate :end_date_is_after_start_date
  accepts_nested_attributes_for :image

  def is_normal_user?
    user_role == 'normal_user'
  end

  def is_manager?
    user_role == 'manager'
  end

  def is_admin?
    user_role == 'admin'
  end

#######
private
#######

def end_date_is_after_start_date
  return if end_date.blank? || start_date.blank?
  if end_date < start_date
    errors.add(:end_date, "cannot be before the start date") 
  end 
end
end

app/models/user_region.rb
class UserRegion < ApplicationRecord
	belongs_to :user
	belongs_to :region
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_place, only: %i[ show edit update destroy ]

  # GET /places or /places.json
  def index
    @places = Place.all
  end

  # GET /places/1 or /places/1.json
  def show
  end

  # GET /places/new
  def new
    set_node
    @place = Place.new
    authorize @place
  end

  # GET /places/1/edit
  def edit
    set_node
  end

  # POST /places or /places.json
  def create
    @place = Place.new(place_params)
     authorize @place

    respond_to do |format|
      if @place.save
        format.html { redirect_to place_url(@place), notice: "Place was successfully created." }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1 or /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to place_url(@place), notice: "Place was successfully updated." }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1 or /places/1.json
  def destroy
    @place.destroy

    respond_to do |format|
      format.html { redirect_to places_url, notice: "Place was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
       authorize @place
    end

    def set_node
      @node = Node.new
      @node = @place.node if @place.present?
    end

    # Only allow a list of trusted parameters through.
    def place_params
      params.require(:place).permit(:place_name, :company_id, node_attributes: {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/user_regions_helper.rb
module UserRegionsHelper
	def all_user_list
		users = User.all
		#users = [users]

	end
end

app/views/places/_form.html.erb
<%= form_with(model: place) do |form| %>
<section>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
        <% place.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-container"> 
    <%= form.label :place_name %>
    <%= form.text_field :place_name, place_holder: 'Place' %>
  </div>

  <div class="custom-select">
    <%= form.collection_select :company_id, Company.order(:id), :id, :name , place_holder: 'Company' %>
    <%= form.label :company %>
  </div>


  <%= form.fields_for :node, @node do |form| %>
  <div class="input-container">
    <%= form.label :place_name %>
    <%= form.text_field :node_name %> 
  </div>  
  <%end %>

  <div class="send-container">
    <%= form.submit %>
  </div>
<% end %>
</section>
<%= render 'partials/js_partial' %>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<div class="content">
<p id="notice"><%= notice %></p>

<h1>Places</h1>

<table class="zui-table">
  <thead>
    <tr>
      <th>Place name</th>
      <th>Node name</th>
      <th>show</th>
      <th>edit</th>
      <th>delete</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.place_name %></td>
        <td><%= place.node&.node_name %></td>
        <td><%= link_to 'Show', place %></td>
        <td><%= link_to 'Edit', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place', new_place_path %>
</div>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Place name:</strong>
  <%= @place.place_name %>
</p>

<p>
  <strong>Company name:</strong>
  <%= @place.company&.name %>
</p>

<p>
  <strong>Node name:</strong>
  <%= @place.node&.node_name %>
</p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>